### ISSUE TITLE
Getting error while using byteData in Image.memory

### ISSUE THREAD

**Issue by suneeltechnew** [marcglasberg/image_pixels#10]
![image](https://user-images.githubusercontent.com/88646798/176106844-ceb9031f-d500-48d3-a5ee-b43a2dab5f26.png)

**Comment by marcglasberg** [comment]
For me to have any chance of understanding the problem you have to provide the complete code that I can run (with main method and all), and make this code as simple as possible. Can you do that, please?

Also, please provide the output of your `flutter doctor`

Thanks!

**Comment by marcglasberg** [comment]
Closing this as I got no response. I'll reopen once I get the info. Thank you.
